main/urls.py
# from django.contrib import admin
# from django.urls import path
# from core.views import index,detalhes,detalhes2
# from reserva.views import reserva_editar,reserva_listar,reserva_remover,reserva_criar
# from stand.views import stand_criar,stand_editar,stand_listar,stand_remover
# from django.conf.urls.static import static
# from django.conf import settings
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('',index,name='index'),
#     path('detalhes/<int:id>/',detalhes,name='detalhes'),
#     path('detalhes2/<int:id>/',detalhes2,name='detalhes2'),
#     path('reserva/',reserva_criar,name='reserva_criar'),
#     path('reserva/remover/<int:id>/',reserva_remover,name='reserva_remover'),
#     path('reserva/editar/<int:id>/',reserva_editar,name='reserva_editar'),
#     path('listar/',reserva_listar,name='reserva_listar'),

#     path('stand/',stand_criar,name='stand_criar'),
#     path('stand/remover/<int:id>/',stand_remover,name='stand_remover'),
#     path('stand/editar/<int:id>/',stand_editar,name='stand_editar'),
#     path('listar2/',stand_listar,name='stand_listar'),
# ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.contrib import admin
from django.urls import path,include
from core.views import HomeView, ReservaDetailView,StandDetailView2,ProfileView

from reserva.views import ReservasListView, ReservaCreateView, ReservaDeleteView, ReservaUpdateView
from stand.views import StandCreateView,StandDeleteView,StandListView,StandUpdateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('',index,name='index'),
  
    path('', HomeView.as_view(), name='index'),
    path('reservas/detail/<int:pk>/', ReservaDetailView.as_view(), name='detalhe'),
    path('stands/detail/<int:pk>/', StandDetailView2.as_view(), name='detalhe2'),
    # path('detalhe/<int:id>/', detalhe_reserva, name='detalhe_reserva'),

    path("", include("users.urls", namespace="users")),
    path('reserva/',ReservaCreateView.as_view(),name='reserva_criar'),
    path('reserva/editar/<int:pk>/',ReservaUpdateView.as_view(), name='reserva_editar'),
    path('reserva/remover/<int:pk>/',ReservaDeleteView.as_view(),name='reserva_remover'),
    path('reserva/listar', ReservasListView.as_view(), name='reserva_listar'),
    
    path('stand/',StandCreateView.as_view(),name='stand_criar'),
    path('stand/editar/<int:pk>/',StandUpdateView.as_view(), name='stand_editar'),
    path('stand/remover/<int:pk>/',StandDeleteView.as_view(),name='stand_remover'),
    path('stand/listar',StandListView.as_view(),name='stand_listar'),
    # path('accounts/', include('allauth.urls')),
    path('accounts/profile/',ProfileView.as_view(),name='account_profile'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
# from .views import UserDeleteView, UserUpdateView
from . import views

app_name = "users"
urlpatterns = [
    path('users/form/', views.UserCreateView.as_view(), name='create'),
    path('users/list/', views.UsersListView.as_view(), name='list'),
    # Users authentication
    path('authentication/login/', auth_views.LoginView.as_view(), name='login'),
    path('authentication/logout/', auth_views.LogoutView.as_view(), name='logout'),
#     path('user/editar/<int:pk>/',UserUpdateView.as_view(), name='editar'),
#     path('user/remover/<int:pk>/',UserDeleteView.as_view(),name='user_remover'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Informe um endereço de e-mail válido.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_superuser = True
        user.email = self.cleaned_data['email']
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages import views
from django.urls import reverse_lazy
from django.views import generic
from users.permissions import GerentePermission

from .forms import UserRegistrationForm
from .filters import UserFilter
from django_filters.views import FilterView
User = get_user_model()

class UserCreateView(views.SuccessMessageMixin, generic.CreateView):
    model = User
    form_class = UserRegistrationForm
    success_url = reverse_lazy("index")
    success_message = "Usuário cadastrado com sucesso!"
    template_name = "users/signup.html"

class UsersListView(GerentePermission,LoginRequiredMixin, FilterView):
    model = User
    paginate_by = 10
    ordering = ["name"]
    filterset_class = UserFilter
    template_name = "users/list.html"

    def get_queryset(self):
        return User.objects.filter()

# class UserDeleteView(LoginRequiredMixin, generic.DeleteView):
#   model = User
#   success_url = reverse_lazy("users:list")
#   template_name = "user/user_confirm_delete.html"
  
# class UserUpdateView( LoginRequiredMixin,views.SuccessMessageMixin,generic.UpdateView):
#   model = User
#   form_class =UserRegistrationForm
#   success_url = reverse_lazy("users:list")
#   success_message= 'Alterações salvas!'
#   template_name = "user/signup.html"

users/templates/users/list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<form method="GET" action="{% url 'users:list' %}" autocomplete="off">
    <section class="form container-fluid p-5x">
        <div class="row">
          <div class="col-12 mx-0 mt-3">
            <p>{% translate "Filtros" %}</p>
            <span class="br-divider sm mt-3"></span>
          </div>
          <div class="col-12 mx-0 mt-3">
            <div class="br-input input-inline">
              <div class="input-content">

                
                <div class="d-flex">
                    <div class="form-group">
                    {{ filter.form.username.label_tag }}
                    {{ filter.form.username }}
                    </div>

                    <div class="col-12 mx-0 mt-4">
                        <button  style=' background-color:#7386D5;  color:white' class="btn " type="submit" name="filtrar">
                          <i class="fa fa-filter"></i>
                          {% translate "Filtrar" %}
                        </button>
                      </div>
                </div>


              
              
            </div>
          </div>
          
        </div>
      </section>
    </form> 
<div class="mt-5">
  <h2>Lista de Usuarios
  </h2>

  <table class="table">
    <thead class="thead-light">
        <tr>
            <th style='font-size:20px'scope="col">Nome de Usuário</th>
            <th style='font-size:20px'scope="col">Email</th>
           
            <th style='font-size:20px'scope="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        
        {% for object in object_list %}
        
        <tr>
            
            <td>{{object.username}}</td>
            <td>{{object.email}}</td>
            <td>
                <a style='color:#7386D5'href=""><i class="fas fa-edit"></i></a>
                <a style='color:#7386D5'href=""><i class="fas fa-trash-alt"></i></a>
                <a style='color:#7386D5'href="{"><i class="fas fa-search"></i></a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">
            <p>Não existem reservas cadastradas.</p>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="mb-3">
    <a style='background-color:#7386D5; color:white 'href="{% url 'users:create' %}" class="btn btn">Cadastrar </a>
</div>
</div>

{% if page_obj.has_other_pages %}
<nav>
    <ul class="
pagination justify-content-center
">
        {% if page_obj.has_previous %}
            <li style='color:black;' class="page-item">
                <a style=' color:black;' class="page-link" href="?page=1">
                   Primeiro
                </a>
            </li>
            <li class="page-item">
                <a style=' color:black;' class="page-link" href="?page={{ page_obj.previous_page_number }}">
                   Anterior
                </a>
            </li>
        {% endif %}

        {% for page_number in page_obj.paginator.page_range %}
            {% if page_number <= page_obj.number|add:3 and page_number >= page_obj.number|add:-3 %}
                {% if page_obj.number == page_number %}
                    <li class="page-item active">
                        <a style=' color:black;' class="page-link" href="?page={{ page_number }}">
                            {{ page_number }}
                        </a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a style='color:black;'class="page-link" href="?page={{ page_number }}">
                            {{ page_number }}
                        </a>
                    </li>
                {% endif %}
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
                <a style='color:black;' class="page-link" href="?page={{ page_obj.next_page_number }}">
                    Próximo
                </a>
            </li>
            <li class="page-item">
                <a style='color:black;'class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                    Final
                </a>
            </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}

users/templates/users/signup.html
{% extends "base2.html" %}

{% block title %}Cadastrar-se{% endblock %}

{% load i18n %}

{% block head_title %}{% trans "Signup" %}{% endblock head_title %}

{% block content %}

<ul class="nav nav-pills nav-justified  mt-4 mb-3" id="ex1" role="tablist">
  <li class="nav-item" role="presentation">
    <a class="nav-link  "  id="tab-login" data-mdb-toggle="pill" href="{% url 'users:login' %}" role="tab"
       aria-selected="true" >Login</a>
  </li>
  <li class="nav-item" role="presentation">
    <a class="nav-link active "  id="tab-register" data-mdb-toggle="pill" href="" role="tab"
      aria-selected="false">Register</a>
  </li>
</ul>
<h1>{% trans "Cadastro" %}</h1>



<p>Já tem uma conta? <a href="{% url 'users:login' %}" style="color:#7386D5" >Entre agora</a></p>




<form class="signup" id="signup_form" method="POST" action="">
  {% csrf_token %}

  <div class="validate-input m-b-16 br-input" data-validate="Please enter username">
    <label for="id_login">{% translate "Nome:" %}</label>
    <div class="form-outline mb-4 form-control">
      <div class="ml-3">{{ form.username }}</div>
    </div>
  </div>




  <div class="validate-input m-b-16 br-input" data-validate="Please enter email">
    <label for="id_login">{% translate "Email:" %}</label>
    <div class="form-outline mb-4 form-control">
      <div class="ml-3">{{ form.email }}</div>
    </div>
  </div>
  <label for="id_login">{% translate "Senha:" %}</label>
  <div class="validate-input m-b-16 br-input" data-validate="Please enter password">
    <div class="form-outline mb-4 form-control">
      <div class="ml-3">{{ form.password1 }}</div>
    </div>
  </div>
  <div class="validate-input m-b-16 br-input" data-validate="Please confirm your password">
    <label for="id_login">{% translate "Digite sua senha:" %}</label>
    <div class="form-outline mb-4 form-control">
      <div class="ml-3">{{ form.password2 }}</div>
    </div>
  </div>
  {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
{% endif %}
  
  <div class="text-right p-t-13 p-b-23  mb-2">
  

  <a class="button secondaryAction txt2" href="">Forgot password?</a>

  </div>

  <div class="container-login100-form-btn">
    <button class="btn btn btn-block mb-3" style="background-color:#7386D5; color:white" type="submit">{% translate 'Cadastrar' %}</button>
  </div>


</form>
{% endblock content %} 

users/templates/users/users_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Cadastro de Usuario
{% endblock %}

{% block content %}
<div class="mt-5">
  
  <form method="post">
    <section class="form container-fluid p-5x">
      {% csrf_token %}
      <p> Você tem certeza que deseja excluir "{{ object.username }}"?</p>
      {{ form }}
    </section>

    <a href="{% url 'users:list' %}" style=' background-color:#7386D5;  color:white' class="btn ">
      Voltar
    </a>
    <button style=' background-color:#7386D5 ; color:white ' type="submit" class="btn ">
      Confirmar
    </button>
  </form>

</div>
{% endblock %}