main/urls.py
# from django.contrib import admin
# from django.urls import path
# from core.views import index,detalhes,detalhes2
# from reserva.views import reserva_editar,reserva_listar,reserva_remover,reserva_criar
# from stand.views import stand_criar,stand_editar,stand_listar,stand_remover
# from django.conf.urls.static import static
# from django.conf import settings
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('',index,name='index'),
#     path('detalhes/<int:id>/',detalhes,name='detalhes'),
#     path('detalhes2/<int:id>/',detalhes2,name='detalhes2'),
#     path('reserva/',reserva_criar,name='reserva_criar'),
#     path('reserva/remover/<int:id>/',reserva_remover,name='reserva_remover'),
#     path('reserva/editar/<int:id>/',reserva_editar,name='reserva_editar'),
#     path('listar/',reserva_listar,name='reserva_listar'),

#     path('stand/',stand_criar,name='stand_criar'),
#     path('stand/remover/<int:id>/',stand_remover,name='stand_remover'),
#     path('stand/editar/<int:id>/',stand_editar,name='stand_editar'),
#     path('listar2/',stand_listar,name='stand_listar'),
# ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.contrib import admin
from django.urls import path,include
from core.views import HomeView, ReservaDetailView,StandDetailView2,ProfileView

from reserva.views import ReservasListView, ReservaCreateView, ReservaDeleteView, ReservaUpdateView
from stand.views import StandCreateView,StandDeleteView,StandListView,StandUpdateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('',index,name='index'),
  
    path('', HomeView.as_view(), name='index'),
    path('reservas/detail/<int:pk>/', ReservaDetailView.as_view(), name='detalhe'),
    path('stands/detail/<int:pk>/', StandDetailView2.as_view(), name='detalhe2'),
    # path('detalhe/<int:id>/', detalhe_reserva, name='detalhe_reserva'),

    path("", include("users.urls", namespace="users")),
    path('reserva/',ReservaCreateView.as_view(),name='reserva_criar'),
    path('reserva/editar/<int:pk>/',ReservaUpdateView.as_view(), name='reserva_editar'),
    path('reserva/remover/<int:pk>/',ReservaDeleteView.as_view(),name='reserva_remover'),
    path('reserva/listar', ReservasListView.as_view(), name='reserva_listar'),
    
    path('stand/',StandCreateView.as_view(),name='stand_criar'),
    path('stand/editar/<int:pk>/',StandUpdateView.as_view(), name='stand_editar'),
    path('stand/remover/<int:pk>/',StandDeleteView.as_view(),name='stand_remover'),
    path('stand/listar',StandListView.as_view(),name='stand_listar'),
    # path('accounts/', include('allauth.urls')),
    path('accounts/profile/',ProfileView.as_view(),name='account_profile'),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
# from .views import UserDeleteView, UserUpdateView
from . import views

app_name = "users"
urlpatterns = [
    path('users/form/', views.UserCreateView.as_view(), name='create'),
    path('users/list/', views.UsersListView.as_view(), name='list'),
    # Users authentication
    path('authentication/login/', auth_views.LoginView.as_view(), name='login'),
    path('authentication/logout/', auth_views.LogoutView.as_view(), name='logout'),
#     path('user/editar/<int:pk>/',UserUpdateView.as_view(), name='editar'),
#     path('user/remover/<int:pk>/',UserDeleteView.as_view(),name='user_remover'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

  <title>
    {% block title %}
    FINECAP
    {% endblock %}
  </title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet" />
  <!-- Bootstrap CSS CDN -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous" />
  <!-- Our Custom CSS -->

  <link rel="stylesheet" href="{% static 'css/style2.css' %}" />
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css" />

  <!-- Font Awesome JS -->
  <script src="js/jquery-1.2.6.pack.js" type="text/javascript"></script>
  <script src="js/jquery.maskedinput-1.1.4.pack.js" type="text/javascript" />
  </script>

  <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
    integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
    crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
    integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
    crossorigin="anonymous"></script>
</head>

<body>
  <div class="wrapper">
    <!-- Sidebar -->
    <nav id="sidebar">
      <div class="sidebar-header">
        <h3 class="text-center">Finecap</h3>
      </div>

      <ul class="list-unstyled components">
        <li>
          <a href="{% url 'index' %}">Inicio</a>
        </li>
        <li>
          <a href="{% url 'reserva_listar' %}">Reservas</a>
        </li>
        <li>
          <a href="{% url 'stand_listar' %}">Stands</a>
        </li>

       <li>
          <a href="{% url 'users:list' %}">Usuarios</a>
        </li> 

        <li>
          <a href="{% url 'users:logout' %}">Sair</a>
        </li> 

      </ul>

    </nav>



    <!-- Page Content -->
    <div id="content">
      {% comment %} <div class="d-flex justify-content-end">
        <button style='background-color:#7386D5;' type="button" id="sidebarCollapse" class="btn btn-info">
          <i class="fas fa-align-left"></i>
      </div>
      </button> {% endcomment %}
      <main role="main" class="container">
        {% if messages %}
        {% include 'layouts/sms.html' %}
        {% endif %}

        {% block alerts %}

        {% endblock %}

        {% block content %}

        {% endblock %}
      </main>
    </div>
  </div>

  <!-- jQuery CDN - Slim version (=without AJAX) -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <!-- Popper.JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
    integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
    crossorigin="anonymous"></script>
  <!-- Bootstrap JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
    integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
    crossorigin="anonymous"></script>
  <!-- jQuery Custom Scroller CDN -->
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

  <script type="text/javascript">
    $(document).ready(function () {
      $('#sidebar').mCustomScrollbar({
        theme: 'minimal'
      })

      $('#sidebarCollapse').on('click', function () {
        $('#sidebar, #content').toggleClass('active')
        $('.collapse.in').toggleClass('in')
        $('a[aria-expanded=true]').attr('aria-expanded', 'false')
      })
    })
  </script>

  {% block modal %}{% endblock %}

  {% block javascript %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
    integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"
    integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  <script>
    $(document).ready(function () {
      $('.money').mask('0000,00', { reverse: true })
    })
  </script>



  <script type="text/javascript">
    $(document).ready(function () {
      $(".cnpj").mask("99.999.999/9999-99");
    });
  </script>
  {% endblock javascript %}



</body>

</html>

templates/base2.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

  <title>
    {% block title %}
    FINECAP
    {% endblock %}
  </title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet" />
  <!-- Bootstrap CSS CDN -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
    integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous" />
  <!-- Our Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/style3.css' %}" />
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css" />

  <!-- Font Awesome JS -->
  <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
    integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
    crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
    integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
    crossorigin="anonymous"></script>
</head>

<body>
 
    <!-- Sidebar -->
    

    <!-- Page Content -->

      {% comment %} <div class="d-flex justify-content-end">
        <button style='background-color:#7386D5;' type="button" id="sidebarCollapse" class="btn btn-info">
          <i class="fas fa-align-left"></i>
      </div>
      </button> {% endcomment %}
      <main role="main" class="container">
        {% if messages %}
        {% include 'layouts/sms.html' %}
        {% endif %}

        {% block alerts %}

        {% endblock %}

        {% block content %}

        {% endblock %}
      </main>
    </div>
  </div>

  <!-- jQuery CDN - Slim version (=without AJAX) -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <!-- Popper.JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
    integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
    crossorigin="anonymous"></script>
  <!-- Bootstrap JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
    integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
    crossorigin="anonymous"></script>
  <!-- jQuery Custom Scroller CDN -->
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

  <script type="text/javascript">
    $(document).ready(function () {
      $('#sidebar').mCustomScrollbar({
        theme: 'minimal'
      })

      $('#sidebarCollapse').on('click', function () {
        $('#sidebar, #content').toggleClass('active')
        $('.collapse.in').toggleClass('in')
        $('a[aria-expanded=true]').attr('aria-expanded', 'false')
      })
    })
  </script>

  {% block modal %}{% endblock %}

  {% block javascript %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
    integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"
    integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  <script>
    $(document).ready(function () {
      $('.money').mask('0000,00', { reverse: true })
    })
  </script>
  {% endblock javascript %}

</body>

</html>